package analyze_test

import (
	"bytes"
	"os"
	"os/exec"
	"path/filepath"
	"testing"

	"github.com/quantum3ap/binsize/internal/analyze"
	"github.com/quantum3ap/binsize/internal/diffreport"
	"github.com/quantum3ap/binsize/internal/report"
)

// Fixtures are compiled at test time rather than committed to testdata/.
// Committed binaries are multi-megabyte, go stale against new toolchains, and
// cannot be regenerated by a contributor who hits a parsing bug. Building them
// here costs a few seconds and always matches the local Go version.

const fixtureSmall = `package main

import "fmt"

func main() { fmt.Println("hello") }
`

const fixtureLarge = `package main

import (
	"encoding/json"
	"fmt"
	"net/http"
)

func main() {
	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		json.NewEncoder(w).Encode(map[string]string{"ok": "yes"})
	})
	fmt.Println("hello")
}
`

// fixtureZeroFill has a large zero-initialised global: it occupies virtual
// memory but essentially no file bytes. It is a regression test for
// attribution running away on PE and Mach-O, where symbol sizes are derived
// from address gaps and a zero-fill section can span hundreds of megabytes.
const fixtureZeroFill = `package main

import "fmt"

var buf [200 << 20]byte

func main() { fmt.Println(buf[0]) }
`

func build(t *testing.T, src, goos, goarch string) string {
	t.Helper()
	if _, err := exec.LookPath("go"); err != nil {
		t.Skip("go toolchain not available")
	}
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "main.go"), []byte(src), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "go.mod"),
		[]byte("module fixture\n\ngo 1.22\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	out := filepath.Join(dir, "app")
	if goos == "windows" {
		out += ".exe"
	}
	cmd := exec.Command("go", "build", "-o", out, ".")
	cmd.Dir = dir
	cmd.Env = append(os.Environ(), "GOOS="+goos, "GOARCH="+goarch, "CGO_ENABLED=0")
	if b, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("build %s/%s: %v\n%s", goos, goarch, err, b)
	}
	return out
}

func analyzeFixture(t *testing.T, src, goos, goarch string) *report.Report {
	t.Helper()
	r, err := analyze.Run(build(t, src, goos, goarch),
		analyze.Options{Label: "cli", ToolVersion: "test"})
	if err != nil {
		t.Fatalf("analyze %s/%s: %v", goos, goarch, err)
	}
	return r
}

// TestFormats walks ELF, Mach-O and PE through parsing and schema validation.
func TestFormats(t *testing.T) {
	cases := []struct {
		goos, goarch, format, method string
	}{
		{"linux", "amd64", "elf", "symtab"},
		{"linux", "arm64", "elf", "symtab"},
		{"darwin", "amd64", "macho", "gap"},
		{"darwin", "arm64", "macho", "gap"},
		{"windows", "amd64", "pe", "gap"},
	}
	for _, c := range cases {
		t.Run(c.goos+"_"+c.goarch, func(t *testing.T) {
			r := analyzeFixture(t, fixtureLarge, c.goos, c.goarch)

			if r.Target.Format != c.format {
				t.Errorf("format = %q, want %q", r.Target.Format, c.format)
			}
			if r.Target.OS != c.goos || r.Target.Arch != c.goarch {
				t.Errorf("target = %s/%s, want %s/%s",
					r.Target.OS, r.Target.Arch, c.goos, c.goarch)
			}
			if r.Totals.AttributionMethod != c.method {
				t.Errorf("attribution method = %q, want %q",
					r.Totals.AttributionMethod, c.method)
			}
			if r.Toolchain.Compiler != "go" || r.Toolchain.Version == "" {
				t.Errorf("toolchain = %q %q, want go with a version",
					r.Toolchain.Compiler, r.Toolchain.Version)
			}
			if r.Target.Stripped {
				t.Error("unstripped binary reported as stripped")
			}

			// Attribution must stay inside the file. This is the invariant that
			// the zero-fill bug violated by a factor of 100.
			if r.Totals.Overcounted {
				t.Errorf("attribution %d exceeds file size %d",
					r.Totals.Attributed, r.Totals.FileSize)
			}
			if r.Totals.Attributed <= 0 {
				t.Error("no bytes attributed")
			}
			if r.Totals.SymbolCount == 0 {
				t.Error("no symbols found")
			}

			// Real Go packages must be recognisable, not mangled fragments.
			want := map[string]bool{"net/http": false, "encoding/json": false, "runtime": false}
			for _, g := range r.Groups {
				if _, ok := want[g.Name]; ok {
					want[g.Name] = true
				}
			}
			for name, found := range want {
				if !found {
					t.Errorf("expected group %q not attributed", name)
				}
			}
		})
	}
}

// TestZeroFillDoesNotInflateAttribution guards the PE/Mach-O sizing bug: a
// 200 MB zero-fill global must not be attributed to the preceding symbol.
func TestZeroFillDoesNotInflateAttribution(t *testing.T) {
	for _, goos := range []string{"windows", "darwin", "linux"} {
		t.Run(goos, func(t *testing.T) {
			r := analyzeFixture(t, fixtureZeroFill, goos, "amd64")
			if r.Totals.Overcounted {
				t.Fatalf("attributed %d bytes of a %d byte file",
					r.Totals.Attributed, r.Totals.FileSize)
			}
			if r.Totals.Attributed > r.Totals.FileSize {
				t.Fatalf("attributed %d > file size %d",
					r.Totals.Attributed, r.Totals.FileSize)
			}
		})
	}
}

// TestSchemaRoundTrip checks a report survives encode/decode unchanged, since
// baselines are committed as JSON and read back by a later run.
func TestSchemaRoundTrip(t *testing.T) {
	r := analyzeFixture(t, fixtureSmall, "linux", "amd64")

	var buf bytes.Buffer
	if err := r.Write(&buf); err != nil {
		t.Fatal(err)
	}
	got, err := report.Read(&buf)
	if err != nil {
		t.Fatal(err)
	}
	if got.Fingerprint() != r.Fingerprint() {
		t.Error("fingerprint changed across serialization")
	}
	if got.Totals.FileSize != r.Totals.FileSize ||
		got.Totals.Attributed != r.Totals.Attributed ||
		len(got.Groups) != len(r.Groups) {
		t.Error("totals or groups changed across serialization")
	}
}

func TestSchemaRejectsFutureVersion(t *testing.T) {
	in := bytes.NewBufferString(`{"schema_version": 9999}`)
	if _, err := report.Read(in); err == nil {
		t.Fatal("expected rejection of a future schema version")
	}
}

// TestDiffDetectsGrowth is the end-to-end path: two binaries, two reports,
// one diff, correct attribution of the growth.
func TestDiffDetectsGrowth(t *testing.T) {
	base := analyzeFixture(t, fixtureSmall, "linux", "amd64")
	head := analyzeFixture(t, fixtureLarge, "linux", "amd64")

	d := diffreport.Compute(base, head)
	if !d.Comparable {
		t.Fatalf("identical build settings reported incomparable: %s", d.Reason)
	}
	if d.Delta <= 0 {
		t.Fatalf("expected growth, got delta %d", d.Delta)
	}

	var found bool
	for _, g := range d.Groups {
		if g.Name == "net/http" && g.New && g.Delta > 0 {
			found = true
		}
	}
	if !found {
		t.Error("net/http should appear as a new group with positive delta")
	}

	md := diffreport.Markdown(d, 10*1024, 15)
	for _, want := range []string{diffreport.CommentMarker, "grew", "net/http", "| Package |"} {
		if !bytes.Contains([]byte(md), []byte(want)) {
			t.Errorf("markdown missing %q", want)
		}
	}
}

// TestIncomparableSuppressesAttribution covers the guard that keeps the tool
// from reporting a toolchain difference as a source regression.
func TestIncomparableSuppressesAttribution(t *testing.T) {
	base := analyzeFixture(t, fixtureLarge, "linux", "amd64")

	head := analyzeFixture(t, fixtureLarge, "linux", "amd64")
	head.Toolchain.BuildFlags = "-ldflags=-s -w"

	d := diffreport.Compute(base, head)
	if d.Comparable {
		t.Fatal("differing build flags must not be comparable")
	}
	if len(d.Groups) != 0 {
		t.Error("attribution must be suppressed when incomparable")
	}
	// The total is still meaningful and must survive.
	if d.HeadTotal == 0 {
		t.Error("total file size should still be reported")
	}
	if !bytes.Contains([]byte(diffreport.Markdown(d, 0, 15)), []byte("not comparable")) {
		t.Error("markdown should say the reports are not comparable")
	}
}

// TestCrossFormatIsIncomparable: an ELF baseline must never be diffed against
// a Mach-O head, both because the platform differs and because symtab and gap
// attribution are not on the same scale.
func TestCrossFormatIsIncomparable(t *testing.T) {
	elf := analyzeFixture(t, fixtureLarge, "linux", "amd64")
	macho := analyzeFixture(t, fixtureLarge, "darwin", "amd64")

	if ok, _ := report.Comparable(elf, macho); ok {
		t.Fatal("ELF and Mach-O reports must not be comparable")
	}
}
